// LOCALHOST 
### Get all contacts
GET http://localhost:8000/contacts 

### Get one contact
GET http://localhost:8000/contacts/66f8535309b4b094b83353e5

### Create a contact
POST http://localhost:8000/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Mason",
    "lastName": "Weber",
    "email": "masonweber@gmail.com",
    "favoriteColor": "purple",
    "birthday": "2003-09-08"
}

### Update a contact
PUT http://localhost:8000/contacts/670b2fe2c62fe9a8fcceea7d
content-type: application/json

{
    "firstName": "Mason",
    "lastName": "Weber",
    "email": "webermason@yahoo.com",
    "favoriteColor": "black",
    "birthday": "2003-09-08"
}

### Delete a contact
DELETE http://localhost:8000/contacts/670b2fe2c62fe9a8fcceea7d



// PRODUCTION Deploy 
###
GET https://web-services-w04.onrender.com/contacts
###

### Get one contact
GET https://web-services-w04.onrender.com/contacts/66f8535309b4b094b83353e5

### Create a contact
POST https://web-services-w04.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Mason",
    "lastName": "Weber",
    "email": "masonweber@gmail.com",
    "favoriteColor": "purple",
    "birthday": "2003-09-08"
}

### Update a contact
PUT https://web-services-w04.onrender.com/contacts/6700ed414b6ac27e1c307d63
content-type: application/json

{
    "firstName": "Mason",
    "lastName": "Weber",
    "email": "webermason@yahoo.com",
    "favoriteColor": "black",
    "birthday": "2003-09-08"
}

### Delete a contact
DELETE https://web-services-w04.onrender.com/contacts/670b4f0330c72896fe363c78
