// LOCALHOST 
### 
GET http://localhost:8000/contacts 
### 
GET http://localhost:8000/contacts/66f8535309b4b094b83353e5
### 
GET http://localhost:8000/contacts/66f8535e09b4b094b83353e6
### 
GET http://localhost:8000/contacts/66f8536809b4b094b83353e7
###
GET http://localhost:8000/contacts/66f8536f09b4b094b83353e8

// PRODUCTION Deploy 
###
GET https://mongodbpractice-m3a2.onrender.com/contacts/66f8535309b4b094b83353e5
###
GET https://mongodbpractice-m3a2.onrender.com/contacts/66f8535e09b4b094b83353e6
###
GET https://mongodbpractice-m3a2.onrender.com/contacts/66f8536809b4b094b83353e7
###
GET https://mongodbpractice-m3a2.onrender.com/contacts/66f8536f09b4b094b83353e8
###
GET https://mongodbpractice-m3a2.onrender.com/contacts